### ISSUE TITLE
Create scheduled database backups

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#169]
## Problem

OIM require database snapshots to be placed in a volume called "archive". These snapshots shall be created automatically on a schedule.

## Feature

* Create a persistent volume claim - confirm with OIM naming ("archive"?) and location (one shared for all workloads: sdis, wastd, tsc, _etc._ or one for each workload?) of a size within the k3s cluster's allocation limits but large enough to hold db dumps
* Mount volume to SDIS PROD, SDIS UAT, and a new container running the archival cronjobs
* Create a container with 

  * a **daily** cronjob running a script to pg_dump PROD db to file `sdis.dump`, then pg_restore UAT db from file `sdis.dump`
  * a **weekly** cronjob to pg_dump PROD to a dated snapshot, e.g. `2022-01-01_sdis.dump`
  * somehow prune old snapshots (ideally when they've been harvested for long term archival by OIM)

## Questions to OIM
* Which namespace for the volume: default or per app (sdis, wastd, tsc, _etc._)
* What name for the volume: "archive"?
* Any preferences for db snapshot frequency and naming scheme?

**Comment by florianm** [comment]
rclone media and db snapshots to sharepoint: https://dev.azure.com/dbca-wa/oim-docs/_wiki/wikis/OIM%20Technical%20Documentation/1287/Rclone?anchor=creating-a-remote-for-sharepoint

**Comment by ben3000** [comment]
This issue is stale.
