### ISSUE TITLE
Define scope of SCMT preread

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#177]
## Problem

Adding new Divisions increases the inherent BCS scope of SCMT to include other Divisions as well.

Current scope: All ConceptPlans and ProjectClosures "in approval".

## Feature

Does the SCMT intend to discuss Projects of Divisions outside BCS as well?
If not, are there other committees that SDIS needs to shortlist Documents for?

**Comment by ben3000** [comment]
BCS only manages its own projects, not those from other divisions.

**Comment by florianm** [comment]
SCMT discusses approval of BCS projects only. The template tag `scmt_preread` needs to filter to BCS Division.
Other Divisions might want their own committee, which is a new feature to add.
