### ISSUE TITLE
Enable external logins

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#181]
## Problem

Third parties might want to access SDIS, e.g.

* Students or academic supervisors want to contribute to the annual progress report on their projects (StudentReport).
* Animal Ethics Committee members want to update the AEC approval field in any of the ProjectPlans.

## Feature

To get SDIS onto auth2, we need to confirm the specs. Thinking about this logically, the specs could be quite simple:

* Any member of the public can login to SDIS, but initially and until given permission, does not see any content
* Any SDIS user shall be able to view and edit any projects and their documentation where they are part of the project team list
* Who should be able to see the annual report? DBCA staff (=anyone with a DBCA email address) could be added as viewers automatically.
* Special roles (Animal Ethics Committee - they can be external) are allocated via User Groups added to a User profile by an admin. These will give write access to any ProjectPlan.

**Comment by ben3000** [comment]
This issue is stale.
