### ISSUE TITLE
Only show Projects and Documents of User.division

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#184]
## Problem

Users from a Division are forbidden to view Projects and Documents of other Divisions.

## Feature

- [x] Project lists, Document lists: View: filter to `project__program__division=User.division`
- [x] User.show_docs: Boolean whether to show docs (BCS users only for now)
- [x] Index page: Show TODO component of portfolio only to BCS.
- [x] Project and Document detail pages: check User.show_docs
- [x] Annual Report: show only to Users in Report.divisions
- [ ] Write functional tests for view restrictions (est 3 days)
- [x] Update docs with explanation of view restrictions

All occurrences in the codebase are tagged with `https://github.com/dbca-wa/sdis/issues/184`. Affected are HTML templates and Python code.

**Comment by florianm** [comment]
Index page for a user without "Division" or a Division other than BCS:
* Menu "Reports" hidden
* Portfolio menu "My TODOs" (Documents pending updates or approval) hidden
* Content "Reports" replaced by message "Currently, only BCS projects participate in annual reporting."
![image](https://user-images.githubusercontent.com/762815/171818018-4d8c9d1d-06bd-43e2-a735-e1114ab233f3.png)

My SDIS Profile (or any staff profile):
* Portfolio menu "My Tasks" (Documents pending updates or approval) hidden (wrinkle: Documents are hidden based on viewing User's Division, not on displayed User's Division)
![image](https://user-images.githubusercontent.com/762815/171818532-a4874c68-f347-4ef6-9834-7da51b92c2b7.png)

Any project page:
* Only tab "Overview" visible, tabs for Documents hidden (wrinkle: based on viewing User's Division, not on Project's Division)
![image](https://user-images.githubusercontent.com/762815/171819000-a2c619b5-6b1c-4c93-9014-1762dfa64bac.png)

**Comment by ben3000** [comment]
This issue is stale.
