### ISSUE TITLE
Improve Project list layout

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#185]
## Feature

- [x] Restrict Project list to User.division unless User is superuser.
- [x] Style Project list like the ARAR progress overview.
- [x] Make Project list filterable by typing on type, title, year/number, team list like current project list.
- [x] Add "Download all Projects as CSV" button.

**Comment by florianm** [comment]
The new behaviour is as follows and needs test coverage (checklist for tests):
 
- [ ] Current Project list (admin change_list) shows Projects of all Divisions and was moved to Superuser only "backstage" menu.
- [ ] New "shiny" Project list is filtered to own Division and linked from menu, index, and search bar. Not paginated, but grouped by Program with expandable details.
- [ ] New Project list is a Django ListView and a departure from the overloaded admin site.
- [ ] New Project list does not filter by Team yet. (Extra plumbing required as it's a M2M).
- [ ] Search box in menu searches for partial match in Project title.
- [ ] Projects breadcrumb links to new Project list.

**Comment by florianm** [comment]
New Project list
![image](https://user-images.githubusercontent.com/762815/171825682-56d3432f-f566-4fd0-bdf5-2376505e667d.png)

Expanding one Program
![image](https://user-images.githubusercontent.com/762815/171825760-45e8914b-0dae-4764-a68b-7302bf3cca18.png)

Expanding a Project (project comments)
![image](https://user-images.githubusercontent.com/762815/171825852-d0ca9353-82a0-46fd-a026-452567373b15.png)

Download all Projects to CSV and filters
![image](https://user-images.githubusercontent.com/762815/171825976-5f692555-7fdb-48a0-b951-137336d10d1b.png)

**Comment by ben3000** [comment]
This issue is stale.
