### ISSUE TITLE
Expand Project List to all Divisions

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#193]
## Problem

We might want to give all SDIS users visibility of all SDIS Divisions' projects.

## Feature

- [ ] Do not filter project list to user's division, instead return all projects.
- [ ] Add top level concertina or heading for division above program and project.
- [ ] Add filter for division.
- [ ] Default list view to filter division to user.division but allow user to change filter.

**Comment by ben3000** [comment]
This issue is stale.
