### ISSUE TITLE
SDIS dumps the project CSV to screen on Safari

### ISSUE THREAD

**Issue by ben3000** [parksandwildlife/sdis#195]
## Problem

Tapping the Download all Projects button on the Browse all Projects page dumps the CSV to screen on Safari.

## Reproducible example

* Step 0: Open the Apple Safari browser on a Mac. (On an iPhone, I'm presented with the option to view or download the result)
* Step 1: Go to https://sdis.dbca.wa.gov.au
* Step 2: Tap on Browse all Projects
* Step 3: Tap the Download all Projects button
* Step 4: Notice that the CSV data is presented in the browser window, rather than as a downloaded file.

**Comment by florianm** [comment]
This sounds like we're missing a content disposition header. Will investigate.
