### ISSUE TITLE
Batch-delete projects

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#24]
Currently fails on FKs along the polymorphic inheritance chain. Need to delete child projects first.

**Comment by florianm** [comment]
Current process:
- delete project on detail view deletes child model (e.g. ScienceProject)
- delete project on list view deletes parent model (Project)

This is a bug in django-polymorphic, TODO port workaround to 1.6: https://gist.github.com/jmurty/2034c24b6f91a3eaf51a

**Comment by idabblewith** [comment]
Batch deletion not required in new app. Problematic projects are displayed in GUI for manual handling by relevant staff.

The new webapp is accessible here:
Frontend: https://github.com/dbca-wa/science-projects-client
Backend: https://github.com/dbca-wa/science-projects-service
