### ISSUE TITLE
Visual Bug: Raw HTML shown for some users on documents

### ISSUE THREAD

**Issue by idabblewith** [parksandwildlife/sdis#252]
The HTML generated from the TinyMCE Editor should not be shown on user-facing pages. In most cases, it is not, however, in some projects it is - for specific users.

This appears to be an issue regarding the user roles in a project (approver and submitter), as the HTML and editor renders ordinarily for most users, in an editable state.

The new editor needs to be user/role-agnostic in it's rendering.

**Comment by ben3000** [comment]
This issue is stale.
