### ISSUE TITLE
Render HTML fields in read-only view

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#44]
admin/includes/field.html l16

content is stored in a string containing HTML.
Render as HTML (|safe doesn't work), or at least strip tags (|striptags doesn't work either).

Note this will introduce a XSS vulnerability for malicious JS embedded in HTML that users copy-paste from outside SDIS.

**Comment by florianm** [comment]
need to strip scripts and styles from user supplied HTML

**Comment by idabblewith** [comment]
Newer Django/Lexical handle user input scripts. Additional code will be added to ensure styles aren't included (where necessary)

The new webapp is accessible here:
Frontend: https://github.com/dbca-wa/science-projects-client
Backend: https://github.com/dbca-wa/science-projects-service
