### ISSUE TITLE
Test user tasklist / portfolio

### ISSUE THREAD

**Issue by florianm** [parksandwildlife/sdis#58]
Create projects to fall into/out of each category of
tasklist/portfolio for users of each role, assert they turn up in the right place

**Comment by idabblewith** [comment]
Issue is stale. New app fetches projects users are involved in to populate tasks and documents

The new webapp is accessible here:
Frontend: https://github.com/dbca-wa/science-projects-client
Backend: https://github.com/dbca-wa/science-projects-service
